# Generated by Django 4.2.2 on 2023-09-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='ai_id',
            new_name='ai',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='style_id',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
