# Generated by Django 4.2.2 on 2023-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_gallery_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
