# Generated by Django 4.2.2 on 2023-09-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
