# Generated by Django 4.2.2 on 2023-10-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_image_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Artysta', 'verbose_name_plural': 'Artyści'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
    ]
