# Generated by Django 4.2.2 on 2023-10-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_artist_options_remove_image_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ai',
            options={'ordering': ['name'], 'verbose_name': 'AI', 'verbose_name_plural': 'AI'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['name'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerie'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['photo'], 'verbose_name': 'Obraz', 'verbose_name_plural': 'Obrazy'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'Temat', 'verbose_name_plural': 'Tematy'},
        ),
    ]
