# Generated by Django 4.2.2 on 2023-11-15 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_subject_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImagePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField()),
                ('seed', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('number_of_images', models.IntegerField()),
                ('number_of_steps', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
